# Generated by Django 3.2.8 on 2021-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('experience', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Comilla', 'Comilla'), ('Narayanganj', '\tNarayanganj')], max_length=100)),
                ('zip', models.PositiveIntegerField()),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_pic')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
